
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myapp-dev-1
    restart: always
    env_file: 
      - .env.dev
    environment:
      - APP_NAME=app1
    ports:
      - "${PORT}:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - myapp-dev-network
  app2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myapp-dev-2
    restart: always
    env_file: 
      - .env.dev
    environment:
      - APP_NAME=app2
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - myapp-dev-network
  app3:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myapp-dev-3
    restart: always
    env_file: 
      - .env.dev
    environment:
      - APP_NAME=app3
    ports:
      - "5002:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - myapp-dev-network

  db:
    image: postgres:16
    container_name: myapp-db-dev
    env_file: 
      - .env.dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myapp-dev-network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin-dev
    env_file: 
      - .env.dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - myapp-dev-network

  nginx:
    image: nginx:latest
    container_name: nginx-dev
    env_file: 
      - .env.dev
    ports:
      - "8080:80"   # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - myapp-dev-network

volumes:
  pgdata_dev:

networks:
  myapp-dev-network:
    driver: bridge
